name: GitHub Actions Demo

on: 
  push:
    branches: ["main"]
    paths-ignore: ["./github/**"]
  pull_request:
    branches: ["main"]
    
  schedule:
    - cron: 15 6 * * 0
  
  workflow_dispatch:
    inputs:
      environment:
        description: 'something'
        required: true
        type: environment
    
jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The event was triggered by: ${{github.event_name}}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      
      - name: "Checkout GitHub action"
        uses: actions/checkout@v2
      - name: List all files
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    runs-on: ubuntu-latest
    needs: [ Build ]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Testing
        run: echo "Testing..."
  
  Load-Test:
    runs-on: ubuntu-latest
    needs: [ Build ]
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Testing
        run: echo "Testing..."
  
  Production:
    runs-on: ubuntu-latest
    needs: [ Test, Load-Test ]
    if: input.environment == "Production"
    steps:
      - name: Step 1
        run: echo "prod"
        
      - name: Step 2
        run: echo "prod 2"







