name: GitHub Actions Demo

on: 
  push:
    branches: ["main"]
    paths-ignore: ["./github/**"]
  pull_request:
    branches: ["main"]
    
  schedule:
    - cron: 15 6 * * 0
  
  workflow_dispatch:
    
jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The event was triggered by: ${{github.event_name}}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
      
      - name: "Checkout GitHub action"
        uses: actions/checkout@v2
      - run: |
          $files = Get-ChildItem -File

          foreach ($file in $files) {
              Write-Output $file.FullName
          }
    
    
